CC = gcc
CFLAGS = -Wall -Werror
TARGETS = TP1_1 TP1_2

all: $(TARGETS)

TP1_1: TP1_1.c
	$(CC) $(CFLAGS) -o TP1_1 TP1_1.c

TP2_2: TP1_2.c
	$(CC) $(CFLAGS) -o TP1_2 TP1_2.c

clean:
	rm -f $(TARGETS) *.o
